[project]
name = 'Autonomous-Vehicle-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.payment-processing]
path = 'contracts/payment-processing.clar'
clarity_version = 2
epoch = 2.5

[contracts.vehicle-registration]
path = 'contracts/vehicle-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
